# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarKevisWilliams_BeAround' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarKevisWilliams_BeAround
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
end
